## **Làm quen PyTorch**

### **Bài tập thực Hành**

#### __Bài 1. Tạo Tensor cơ bản__

Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

In [2]:
import torch
a = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]],
     dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


**Yêu cầu**: Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.

In [12]:
# kich thuoc cuar tensor
print("kich thuoc:", a.shape)
# so chieu cua tensor
print("So chieu:", a.dim())
# kieu du lieu cua tensor
print("kieu du lieu:",a.dtype)

kich thuoc: torch.Size([2, 3])
So chieu: 2
kieu du lieu: torch.int32


#### **Bài 2. Tạo các Tensor thường dùng**
Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [13]:
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[9.7295e-01, 1.1086e-01, 4.7103e-01, 7.4143e-01],
        [1.5405e-01, 2.7959e-01, 5.0702e-01, 8.5235e-04],
        [6.0982e-01, 6.0927e-01, 2.6916e-01, 3.6041e-01]])
tensor([[-1.6939, -0.7025,  0.4104, -1.5006],
        [-0.1282, -0.5350,  0.0342,  1.8991],
        [ 1.1004,  0.6858,  0.4113, -1.1816]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


**Yêu cầu:**

• Nhận xét sự khác nhau giữa torch.rand() và torch.randn():

`torch.rand()`: Tạo tensor với các giá trị ngẫu nhiên tuân theo phân phối đều (uniform distribution) trong khoảng từ [0, 1).

`torch.randn()`:Tạo tensor với các giá trị ngẫu nhiên tuân theo phân phối chuẩn/chuông (normal/gaussian distribution) với trung bình bằng 0 và độ lệch chuẩn bằng 1 (các giá trị có thể âm hoặc lớn hơn 1).

• **Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.**

In [15]:
tensor_10 = torch.ones(5, 5)* 10
print(tensor_10)

tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])


#### **Bài 3. Kiểm tra thông tin Tensor**
Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.


In [16]:
a = torch.zeros(2,3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


**Yêu cầu:** Giải thích ý nghĩa của torch.Size([2, 3, 4])
- Tensor này có tổng cộng 3 chiều (3 cấp độ ngoặc vuông).
- Chiều thứ nhất: Có kích thước là 2 (chứa 2 khối dữ liệu con bên trong).
- Chiều thứ hai (ở giữa): Mỗi khối con có 3 hàng
- Chiều thứ ba : Mỗi hàng có 4 cột (4 phần tử).
- Tổng số phần tử của tensor này là $2 \times 3 \times 4 = 24$ phần tử



#### **Bài 4. Slicing và Indexing**
Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

In [18]:
a = torch.rand(3,4,5)
print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[0.3969, 0.9004, 0.1508, 0.3268, 0.1667],
         [0.7524, 0.9132, 0.4232, 0.8251, 0.8244],
         [0.7652, 0.7715, 0.3489, 0.6392, 0.7164],
         [0.6510, 0.0696, 0.6344, 0.3764, 0.4240]],

        [[0.0327, 0.4453, 0.5713, 0.4611, 0.3528],
         [0.7150, 0.1148, 0.5659, 0.7085, 0.9207],
         [0.2633, 0.8950, 0.0472, 0.4377, 0.0977],
         [0.5370, 0.9818, 0.7968, 0.2722, 0.4356]],

        [[0.0845, 0.8103, 0.2980, 0.0887, 0.3657],
         [0.9588, 0.6802, 0.9254, 0.6947, 0.9799],
         [0.0346, 0.3645, 0.5002, 0.3487, 0.5422],
         [0.3284, 0.5047, 0.4433, 0.4615, 0.8173]]])

Tensor a[1]:
tensor([[0.0327, 0.4453, 0.5713, 0.4611, 0.3528],
        [0.7150, 0.1148, 0.5659, 0.7085, 0.9207],
        [0.2633, 0.8950, 0.0472, 0.4377, 0.0977],
        [0.5370, 0.9818, 0.7968, 0.2722, 0.4356]])

Tensor a[1:, 2:4]:
tensor([[[0.2633, 0.8950, 0.0472, 0.4377, 0.0977],
         [0.5370, 0.9818, 0.7968, 0.2722, 0.4356]],

        [[0.0346, 0.3645, 

**Yêu cầu:**

• Cho biết shape của a[1] và a[1:, 2:4].

- a ban đầu có shape là (3, 4, 5).
- a[1]: Lấy phần tử ở index 1 của chiều thứ nhất, bỏ đi chiều đó $\rightarrow$ Shape là (4, 5).
- a[1:, 2:4]: Lấy từ index 1 đến hết ở chiều 1 (còn lại 2 phần tử), lấy từ index 2 đến trước index 4 ở chiều 2 (còn lại $4 - 2 = 2$ phần tử), và giữ nguyên toàn bộ chiều 3 ($\rightarrow$ 5 phần tử) $\rightarrow$ Shape là (2, 2, 5).

• Thử lấy hai phần tử cuối cùng trên chiều thứ ba.

In [19]:
# Chiều thứ ba là chiều cuối cùng (index -2 đến hết)
print(a[..., -2:])

tensor([[[0.3268, 0.1667],
         [0.8251, 0.8244],
         [0.6392, 0.7164],
         [0.3764, 0.4240]],

        [[0.4611, 0.3528],
         [0.7085, 0.9207],
         [0.4377, 0.0977],
         [0.2722, 0.4356]],

        [[0.0887, 0.3657],
         [0.6947, 0.9799],
         [0.3487, 0.5422],
         [0.4615, 0.8173]]])


### **Bài 5. Reshape và Flatten**
Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

In [17]:
a = torch.randn(3, 4)
print("Original: ")
print(a)
print("\nFlatten:")
print(a.ravel())

print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original: 
tensor([[-0.5541,  1.1735, -0.9427, -0.0309],
        [ 0.8731,  0.4468,  0.3288, -0.8020],
        [ 0.3281, -1.2879, -0.9603,  0.5796]])

Flatten:
tensor([-0.5541,  1.1735, -0.9427, -0.0309,  0.8731,  0.4468,  0.3288, -0.8020,
         0.3281, -1.2879, -0.9603,  0.5796])

Reshape to 3 x 2 x 2:
tensor([[[-0.5541,  1.1735],
         [-0.9427, -0.0309]],

        [[ 0.8731,  0.4468],
         [ 0.3288, -0.8020]],

        [[ 0.3281, -1.2879],
         [-0.9603,  0.5796]]])


**Yêu cầu:**

• Kiểm tra số phần tử trước và sau khi reshape.

- số phần tử trước khi reshape: $3 \times 4 = 12$ phần tử.
- Số phần tử sau khi reshape (thành $3 \times 2 \times 2$ hoặc $2 \times 6$): $3 \times 2 \times 2 = 12$ và $2 \times 6 = 12$.
==> Số phần tử được bảo toàn hoàn toàn (đều là 12 phần tử), miễn là tích các chiều mới bằng tổng số phần tử ban đầu.

• Thử reshape Tensor thành kích thước 2 × 6.

In [22]:
a = torch.randn(3, 4)
# Reshape thành ma trận 2 hàng, 6 cột
print(a.reshape(2, 6))

tensor([[-0.3390,  0.3785, -0.3851, -1.2374, -0.3355,  0.3983],
        [-0.8326,  1.2603,  0.0658,  1.0248, -0.0692, -1.9846]])
