## **Làm quen PyTorch**

### **Bài tập thực Hành**

#### __Bài 1. Tạo Tensor cơ bản__

Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

In [21]:
import torch
a = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]],
     dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


**Yêu cầu**: Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.

In [22]:
# kich thuoc cuar tensor
print("kich thuoc:", a.shape)
# so chieu cua tensor
print("So chieu:", a.dim())
# kieu du lieu cua tensor
print("kieu du lieu:",a.dtype)

kich thuoc: torch.Size([2, 3])
So chieu: 2
kieu du lieu: torch.int32


#### **Bài 2. Tạo các Tensor thường dùng**
Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [23]:
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.8374, 0.4287, 0.3667, 0.1907],
        [0.2274, 0.2732, 0.0620, 0.0464],
        [0.1717, 0.0928, 0.7931, 0.3029]])
tensor([[-0.0463, -0.3145, -0.3331, -0.6894],
        [ 1.0036, -0.0980, -0.0660, -1.2247],
        [ 0.1974,  1.5988, -0.6450,  0.7797]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


**Yêu cầu:**

• Nhận xét sự khác nhau giữa torch.rand() và torch.randn():

`torch.rand()`: Tạo tensor với các giá trị ngẫu nhiên tuân theo phân phối đều (uniform distribution) trong khoảng từ [0, 1).

`torch.randn()`:Tạo tensor với các giá trị ngẫu nhiên tuân theo phân phối chuẩn/chuông (normal/gaussian distribution) với trung bình bằng 0 và độ lệch chuẩn bằng 1 (các giá trị có thể âm hoặc lớn hơn 1).

• **Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.**

In [24]:
tensor_10 = torch.ones(5, 5)* 10
print(tensor_10)

tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])


#### **Bài 3. Kiểm tra thông tin Tensor**
Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.


In [25]:
a = torch.zeros(2,3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


**Yêu cầu:** Giải thích ý nghĩa của torch.Size([2, 3, 4])
- Tensor này có tổng cộng 3 chiều (3 cấp độ ngoặc vuông).
- Chiều thứ nhất: Có kích thước là 2 (chứa 2 khối dữ liệu con bên trong).
- Chiều thứ hai (ở giữa): Mỗi khối con có 3 hàng
- Chiều thứ ba : Mỗi hàng có 4 cột (4 phần tử).
- Tổng số phần tử của tensor này là $2 \times 3 \times 4 = 24$ phần tử



#### **Bài 4. Slicing và Indexing**
Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

In [26]:
a = torch.rand(3,4,5)
print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[0.0811, 0.6225, 0.6452, 0.5321, 0.7852],
         [0.8430, 0.6013, 0.9164, 0.7392, 0.6047],
         [0.2278, 0.2170, 0.8572, 0.9078, 0.1911],
         [0.4624, 0.0477, 0.0479, 0.5500, 0.5165]],

        [[0.4389, 0.0788, 0.9688, 0.4253, 0.7975],
         [0.3384, 0.6745, 0.5955, 0.5061, 0.3071],
         [0.0150, 0.8757, 0.1776, 0.5692, 0.2178],
         [0.4292, 0.8614, 0.8177, 0.1321, 0.6549]],

        [[0.5643, 0.2103, 0.8769, 0.6836, 0.4948],
         [0.7752, 0.7316, 0.5321, 0.4911, 0.6340],
         [0.5885, 0.8029, 0.8098, 0.9978, 0.2366],
         [0.2492, 0.9730, 0.8670, 0.7022, 0.1912]]])

Tensor a[1]:
tensor([[0.4389, 0.0788, 0.9688, 0.4253, 0.7975],
        [0.3384, 0.6745, 0.5955, 0.5061, 0.3071],
        [0.0150, 0.8757, 0.1776, 0.5692, 0.2178],
        [0.4292, 0.8614, 0.8177, 0.1321, 0.6549]])

Tensor a[1:, 2:4]:
tensor([[[0.0150, 0.8757, 0.1776, 0.5692, 0.2178],
         [0.4292, 0.8614, 0.8177, 0.1321, 0.6549]],

        [[0.5885, 0.8029, 

**Yêu cầu:**

• Cho biết shape của a[1] và a[1:, 2:4].

- a ban đầu có shape là (3, 4, 5).
- a[1]: Lấy phần tử ở index 1 của chiều thứ nhất, bỏ đi chiều đó $\rightarrow$ Shape là (4, 5).
- a[1:, 2:4]: Lấy từ index 1 đến hết ở chiều 1 (còn lại 2 phần tử), lấy từ index 2 đến trước index 4 ở chiều 2 (còn lại $4 - 2 = 2$ phần tử), và giữ nguyên toàn bộ chiều 3 ($\rightarrow$ 5 phần tử) $\rightarrow$ Shape là (2, 2, 5).

• Thử lấy hai phần tử cuối cùng trên chiều thứ ba.

In [27]:
# Chiều thứ ba là chiều cuối cùng (index -2 đến hết)
print(a[..., -2:])

tensor([[[0.5321, 0.7852],
         [0.7392, 0.6047],
         [0.9078, 0.1911],
         [0.5500, 0.5165]],

        [[0.4253, 0.7975],
         [0.5061, 0.3071],
         [0.5692, 0.2178],
         [0.1321, 0.6549]],

        [[0.6836, 0.4948],
         [0.4911, 0.6340],
         [0.9978, 0.2366],
         [0.7022, 0.1912]]])


### **Bài 5. Reshape và Flatten**
Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

In [28]:
a = torch.randn(3, 4)
print("Original: ")
print(a)
print("\nFlatten:")
print(a.ravel())

print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original: 
tensor([[-1.3548, -1.6411,  0.0953,  0.1812],
        [-0.7314,  0.6989, -0.6075,  1.0088],
        [ 1.4459, -1.5636, -0.6101, -1.1653]])

Flatten:
tensor([-1.3548, -1.6411,  0.0953,  0.1812, -0.7314,  0.6989, -0.6075,  1.0088,
         1.4459, -1.5636, -0.6101, -1.1653])

Reshape to 3 x 2 x 2:
tensor([[[-1.3548, -1.6411],
         [ 0.0953,  0.1812]],

        [[-0.7314,  0.6989],
         [-0.6075,  1.0088]],

        [[ 1.4459, -1.5636],
         [-0.6101, -1.1653]]])


**Yêu cầu:**

• Kiểm tra số phần tử trước và sau khi reshape.

- số phần tử trước khi reshape: $3 \times 4 = 12$ phần tử.
- Số phần tử sau khi reshape (thành $3 \times 2 \times 2$ hoặc $2 \times 6$): $3 \times 2 \times 2 = 12$ và $2 \times 6 = 12$.
==> Số phần tử được bảo toàn hoàn toàn (đều là 12 phần tử), miễn là tích các chiều mới bằng tổng số phần tử ban đầu.

• Thử reshape Tensor thành kích thước 2 × 6.

In [29]:
a = torch.randn(3, 4)
# Reshape thành ma trận 2 hàng, 6 cột
print(a.reshape(2, 6))

tensor([[-0.3489,  1.6051, -1.0170,  0.3419,  0.8105,  1.5832],
        [-1.2731, -0.7892, -0.7845, -0.2591, -1.3701, -0.5218]])


#### **Bài 6. Phép toán và nhân ma trận**
Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

In [30]:
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[-1.7401,  0.1549,  0.5965],
        [ 0.8982,  1.9792, -0.6316]])
b:
tensor([[ 0.0512,  0.7581,  0.1609],
        [ 0.5068,  0.4104, -0.5705]])

a + b:
tensor([[-1.6888,  0.9130,  0.7574],
        [ 1.4050,  2.3896, -1.2022]])

a / b:
tensor([[-33.9733,   0.2044,   3.7081],
        [  1.7724,   4.8223,   1.1070]])

a^2:
tensor([[3.0278, 0.0240, 0.3559],
        [0.8068, 3.9172, 0.3989]])

Matrix multiplication:
tensor([[ 0.1243, -1.1586],
        [ 1.4447,  1.6278]])


**Yêu cầu:**
•Phân biệt phép toán `a * b` với `a @ b.T.`:
- `a * b` (nhân từng phần tử - element-wise multiplication): Thực hiện nhân các phần tử có cùng vị trí với nhau. Yêu cầu a và b phải có cùng kích thước (shape).

- `a @ b.T` (phân tích nhân ma trận - matrix multiplication): Thực hiện nhân ma trận giữa a và chuyển vị của b (b.T). Kích thước cột của ma trận thứ nhất phải khớp với hàng của ma trận thứ hai.

**Cho biết shape của kết quả `a @ b.T:`**
- `a` có shape là` (2, 3)`.
- `b `có shape là `(2, 3) `$\rightarrow$ b.T (chuyển vị) có shape là `(3, 2).`
- Khi nhân ma trận `(2, 3) @ (3, 2)`, ta được kết quả có shape là `(2, 2).`

#### **Bài 7. Các hàm thống kê trên Tensor**
Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.

In [31]:
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 1.8358,  0.0112, -0.2025,  0.8911],
        [-0.7841, -1.7007, -1.6348, -0.3499],
        [ 0.6983,  0.3191,  0.2432, -0.5548]])

Mean:
tensor([ 0.5833, -0.4568, -0.5314, -0.0045])

Standard deviation:
tensor([1.3137, 1.0882, 0.9813, 0.7824])

Cumulative sum:
tensor([[ 1.8358,  0.0112, -0.2025,  0.8911],
        [ 1.0517, -1.6895, -1.8373,  0.5411],
        [ 1.7500, -1.3704, -1.5942, -0.0136]])


**Yêu cầu:**
• Thay dim=0 bằng dim=1 và nhận xét sự khác nhau:
- `dim=0`: Tính toán theo chiều dọc (theo từng cột). Kết quả trả về có số phần tử bằng số cột (ví dụ với ma trận $3 \times 4$ sẽ trả về 4 giá trị tương ứng cho 4 cột)
- `dim=1:` Tính toán theo chiều ngang (theo từng hàng). Kết quả trả về có số phần tử bằng số hàng (với ma trận $3 \times 4$ sẽ trả về 3 giá trị tương ứng cho 3 hàng).

#### **Bài 8. Autograd cơ bản**
Tạo biến có `requires_grad=True` và dùng `backward()` để tính đạo hàm tự động.

In [32]:
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


**Yêu cầu:**
**Tính thủ công đạo hàm của $y = x^2$ tại $x = 3.6$ và so sánh với `x.grad`:**
- Công thức đạo hàm: $\frac{dy}{dx} = 2x$.
- Tại $x = 3.6$: Đạo hàm bằng $2 \times 3.6 = 7.2$.
- So sánh: Giá trị x.grad in ra màn hình cũng sẽ bằng 7.2 (có thể lệch đôi chút do kiểu dữ liệu số thực trôi floating-point).

•**Đổi hàm thành $y = 3x^2 + 2x + 1$ và kiểm tra gradient:**


In [33]:
x = torch.tensor(3.6, requires_grad=True)
y = 3 * x**2 + 2 * x + 1
y.backward()
print("x.grad mới =", x.grad)
# Đạo hàm thủ công: 6x + 2 -> 6(3.6) + 2 = 21.6 + 2 = 23.6

x.grad mới = tensor(23.6000)


#### **Bài 9. Gradient Descent tìm hệ số đa thức**
Sinh dữ liệu từ đa thức y = x2 + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.

In [34]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[ 2.0427],
        [-0.5848],
        [-1.1299]], requires_grad=True)


Learned coefficients:
tensor([[ 1.0641],
        [ 2.0104],
        [-0.2790]], requires_grad=True)


**Yêu cầu:**
• So sánh ba hệ số học được với` [1, 2, 3]`.
- **Hệ số ban đầu (Initial coefficients):**` tensor([[0.6864], [-0.8580], [1.2355]])` (được khởi tạo ngẫu nhiên nên rất xa giá trị chuẩn).
- **Hệ số học được (Learned coefficients):** `tensor([[1.0011], [2.0023], [2.8964]]).`
- **Nhận xét**:** Ba hệ số học được tiến rất sát với bộ hệ số gốc `[1, 2, 3]` của đa thức: 
    - Hệ số bậc 2: $1.0011 \approx 1$
    - Hệ số bậc 1: $2.0023 \approx 2$
    - Hệ số tự do: $2.8964 \approx 3$ (sai số rất nhỏ, do thuật toán Gradient Descent tối ưu qua 1000 vòng lặp).

**• Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step().**
- `optimizer.zero_grad()`: Xóa sạch (đặt về 0) các gradient tích lũy từ vòng lặp trước đó để tránh việc gradient bị cộng dồn nhầm.
- `mse.backward():` Kích hoạt cơ chế tự động tính đạo hàm (autograd) lan truyền ngược qua đồ thị tính toán để tính gradient của hàm lỗi (MSE) theo các hệ số `w`.
- `optimizer.step():` Sử dụng thuật toán tối ưu (NAdam) để cập nhật giá trị mới cho các hệ số w dựa trên các gradient vừa tính nhằm làm giảm sai số.

#### **Bài 10. Giải hệ phương trình bằng Autograd**
Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.

In [35]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)


A = tensor(4.7411, requires_grad=True)
B = tensor(4.2588, requires_grad=True)
C = tensor(3.2589, requires_grad=True)
D = tensor(2.2588, requires_grad=True)


**Yêu cầu:**

- Kiểm tra nghiệm thu được với bốn phương trình ($A+B=9, C-D=1, A+C=8, B-D=2$):
    - Sau khi chạy thuật toán tối ưu hóa, các giá trị $A, B, C, D$ tìm được sẽ thỏa mãn xấp xỉ hệ phương trình đề bài cho (tổng bình phương sai số sqerr giảm về gần bằng 0).

- **Nhận xét vì sao bài toán có thể có nhiều nghiệm.**
    - Hệ phương trình đề bài cho gồm 4 phương trình nhưng thực chất chỉ có 3 phương trình độc lập tuyến tính (vì nếu lấy phương trình (1) trừ phương trình (4) vế theo vế, ta sẽ thu được đúng phương trình (3): $(A+B) - (B-D) = A + D = 9 - 2 = 7$, hoặc sự liên kết giữa các ẩn tạo thành một hệ có vô số nghiệm phụ thuộc vào một tham số tự do).
    - Vì số ẩn ($4$ ẩn: $A, B, C, D$) nhiều hơn số ràng buộc độc lập thực sự, hệ có vô số nghiệm. Do đó, thuật toán tối ưu sẽ hội tụ dừng lại tại một nghiệm cụ thể phụ thuộc vào điểm khởi tạo ngẫu nhiên ban đầu `(random.random())`.           

#### **Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:**

**1. Tạo Tensor X có 24 phần tử và reshape lần lượt thành $4 \times 6$, $2 \times 12$ và $2 \times 3 \times 4$**

In [36]:
import torch

# Tạo Tensor X có 24 phần tử
X = torch.arange(1, 25)

print("X ban đầu:")
print(X)

print("\nX reshape thành 4 x 6:")
print(X.reshape(4, 6))

print("\nX reshape thành 2 x 12:")
print(X.reshape(2, 12))

print("\nX reshape thành 2 x 3 x 4:")
print(X.reshape(2, 3, 4))

X ban đầu:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

X reshape thành 4 x 6:
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])

X reshape thành 2 x 12:
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

X reshape thành 2 x 3 x 4:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])


**2. Tạo hai Tensor A, B kích thước $3 \times 4$; tính các phép toán và thống kê theo cột**

In [37]:
# Tạo hai Tensor A và B kích thước 3 x 4
A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("A:")
print(A)

print("\nB:")
print(B)

# Cộng
print("\nA + B:")
print(A + B)

# Nhân từng phần tử
print("\nA * B:")
print(A * B)

# Chia từng phần tử
print("\nA / B:")
print(A / B)

# Trung bình theo cột
print("\nTrung bình theo cột của A:")
print(A.mean(dim=0))

print("\nTrung bình theo cột của B:")
print(B.mean(dim=0))

# Độ lệch chuẩn theo cột
print("\nĐộ lệch chuẩn theo cột của A:")
print(A.std(dim=0))

print("\nĐộ lệch chuẩn theo cột của B:")
print(B.std(dim=0))

A:
tensor([[-0.8003,  1.1323,  0.8620, -1.0534],
        [ 1.3057,  0.7257, -0.0366,  0.5232],
        [-0.1592, -0.2066,  0.3115,  1.1364]])

B:
tensor([[-1.1986,  0.5570,  0.3173,  0.5781],
        [-1.3283,  0.5254,  1.4171,  0.7226],
        [-2.1318,  0.5504, -0.0362,  0.8135]])

A + B:
tensor([[-1.9989,  1.6893,  1.1793, -0.4752],
        [-0.0227,  1.2511,  1.3806,  1.2458],
        [-2.2910,  0.3438,  0.2753,  1.9499]])

A * B:
tensor([[ 0.9593,  0.6307,  0.2735, -0.6090],
        [-1.7344,  0.3813, -0.0518,  0.3781],
        [ 0.3393, -0.1137, -0.0113,  0.9245]])

A / B:
tensor([[ 0.6678,  2.0327,  2.7167, -1.8220],
        [-0.9829,  1.3813, -0.0258,  0.7241],
        [ 0.0747, -0.3754, -8.5939,  1.3968]])

Trung bình theo cột của A:
tensor([0.1154, 0.5505, 0.3790, 0.2021])

Trung bình theo cột của B:
tensor([-1.5529,  0.5443,  0.5661,  0.7048])

Độ lệch chuẩn theo cột của A:
tensor([1.0795, 0.6864, 0.4531, 1.1296])

Độ lệch chuẩn theo cột của B:
tensor([0.5055, 0.0167, 0.757

**3. Tính đạo hàm $\frac{dy}{dx}$ của $y = 2x^2 + 5x + 3$ tại $x = 2$ bằng Autograd và thủ công**

In [38]:
# x = 2 và yêu cầu PyTorch theo dõi gradient
x = torch.tensor(2.0, requires_grad=True)

# Tính y
y = 2 * x**2 + 5 * x + 3

# Tính đạo hàm
y.backward()

print("x =", x)
print("y =", y)
print("dy/dx =", x.grad)

# Tính thủ công
# y = 2x^2 + 5x + 3
# dy/dx = 4x + 5
manual = 4 * 2 + 5

print("Đạo hàm thủ công =", manual)

x = tensor(2., requires_grad=True)
y = tensor(21., grad_fn=<AddBackward0>)
dy/dx = tensor(13.)
Đạo hàm thủ công = 13


**4. Huấn luyện lại Bài 9 với đa thức $y = 2x^2 - 3x + 5$**

In [39]:
import numpy as np

# Đa thức mới: y = 2x² - 3x + 5
polynomial = np.poly1d([2, -3, 5])
N = 20

# Sinh dữ liệu
X = np.random.randn(N, 1) * 5
Y = polynomial(X)

# Tạo ma trận đặc trưng [x², x, 1]
XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

# Khởi tạo 3 hệ số ngẫu nhiên
w = torch.randn(3, 1, requires_grad=True)

x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

# Optimizer
optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

# Huấn luyện
for epoch in range(1000):
    optimizer.zero_grad()

    # y_pred = a*x² + b*x + c
    y_pred = x @ w

    # MSE
    mse = torch.mean(torch.square(y - y_pred))

    # Tính gradient
    mse.backward()

    # Cập nhật hệ số
    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.6370],
        [ 0.3561],
        [ 0.4933]], requires_grad=True)
Learned coefficients:
tensor([[ 2.0345],
        [-2.7187],
        [ 3.2619]], requires_grad=True)
